[package]
name = "gbemu"
version = "0.1.0"
authors = ["Sindre Johansen <sindre@iterate.no>"]
edition = "2018"

[dependencies]
structopt = "0.2"
derive_more = "0.14.0"
ctrlc = "3.1.1"
rustyline = "5.0.0"
clap = "2.32.0"
glium = "*"
parking_lot = "0.7.1"
